services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./otel-collector.yml:/etc/otel-collector.yml
    ports:
      - 4317:4317
    networks:
      - shadowlog-network

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - shadowlog-network

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - 16686:16686
    networks:
      - shadowlog-network

  shadowlog:
    build: .
    ports:
      - 3000:3000
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=shadowlog
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_RESOURCE_ATTRIBUTES=service.name=shadowlog,service.version=1.0.0,deployment.environment=dev
    depends_on:
      - otel-collector
      - prometheus
      - jaeger
    command: ["run", "--interval=2", "--port=3000"]
    networks:
      - shadowlog-network

networks:
  shadowlog-network:
    driver: bridge
